name: CustomActionGetWorkflow
on: 
  workflow_dispatch:

jobs:
  changeApproval:
    name: ServiceNow Change Approval
    runs-on: ubuntu-latest
    steps:     
      - name: ServiceNow Change Approval
        uses: ServiceNow/servicenow-devops-change@main
        id: create
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow Change Approval'
          change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","assignment_group":"a715cd759f2002002920bde8132e7018","description":"Automated Software Deployment.","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
          interval: '100'
          timeout: '3600'
  changeApproval2:
    needs: changeApproval
    name: ServiceNow Change Approval2
    runs-on: ubuntu-latest
    steps:     
      - name: ServiceNow Change Approval2
        uses: ServiceNow/servicenow-devops-change@main
        id: create2
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow Change Approval2'
          change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","assignment_group":"a715cd759f2002002920bde8132e7018","description":"Automated Software Deployment.","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
          interval: '100'
          timeout: '3600'

  custom_action_get:
    needs: changeApproval
    runs-on: ubuntu-latest
    outputs:
      changeRequestNumber: ${{ steps.get.outputs.change-request-number }}
    name: A Job to get Change
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Custom Action Get Step
        uses: maheshganji/custom-action-get@main    
        # Uses an action in the root directory
        id: get
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          context-github: ${{ toJSON(github) }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          change-details: '{"build_number":"","pipeline_name":"123","stage_name":"ServiceNow Change Approval"}' #Working Version
          continue-on-error: true
      - name: Output of Get
        run: echo "change-request-number = ${{ steps.get.outputs.change-request-number }}" >> $GITHUB_OUTPUT
         #run: echo "The Status of Update Change Request Details => ${{ steps.update.outputs.change-request-number }}"
         
      - name: Checkout
        uses: actions/checkout@v3
      - name: Custom Action Update Step
        uses:  maheshganji/custom-action-update@master
#         maheshganji/custom-action-update@v1.1     
        # Uses an action in the root directory
        id: update1
        with:
          change-request-number: ${{steps.get.outputs.change-request-number}}# Active CR
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          context-github: ${{ toJSON(github) }}
          change-request-details: '{ "work_notes":"Testing123","short_description":"update function changed","description":"updated description"}' #Working Version
      - name: Output of Update
        run: echo "The Status of Update Change Request Details => ${{ steps.update1.outputs.status }}"  
        
        
        
  custom_action_get2:
    needs: changeApproval2
    runs-on: ubuntu-latest
    outputs:
      changeRequestNumber2: ${{ steps.get2.outputs.change-request-number }}
    name: A Job to get Change2
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Custom Action Get Step2
        uses: maheshganji/custom-action-get@main    
        # Uses an action in the root directory
        id: get2
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          context-github: ${{ toJSON(github) }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          change-details: '{"build_number":"","pipeline_name":"","stage_name":"ServiceNow Change Approval"}' #Working Version
      - name: Output of Get
        run: echo "change-request-number = ${{ steps.get2.outputs.change-request-number }}" >> $GITHUB_OUTPUT
